import { useEffect } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface CardBalance {
  id: string;
  user_id: string;
  card_id: string;
  amount: number;
  currency: string;
  created_at: string;
  updated_at: string;
}

export function useCardBalance(cardId?: string) {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  useEffect(() => {
    if (!user || !cardId) return;

    const channel = supabase
      .channel(`card-balance-${cardId}`)
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "card_balances",
          filter: `card_id=eq.${cardId}`,
        },
        () => {
          queryClient.invalidateQueries({
            queryKey: ["cardBalance", user.id, cardId],
          });
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [user, cardId, queryClient]);

  return useQuery({
    queryKey: ["cardBalance", user?.id, cardId],
    enabled: !!user && !!cardId,
    queryFn: async () => {
      if (!user || !cardId) return null;

      // Cast to avoid temporary type mismatch until autogenerated DB types refresh
      const { data, error } = await (supabase as any)
        .from("card_balances")
        .select("*")
        .eq("user_id", user.id)
        .eq("card_id", cardId)
        .maybeSingle();

      if (error) throw error;
      return data as CardBalance | null;
    },
  });
}
